# Generated by Django 3.0.4 on 2020-05-10 14:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20200510_1444'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Customer',
        ),
    ]
