# Generated by Django 3.0.4 on 2020-05-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Starter', 'starter'), ('Basic', 'basic'), ('Pro', 'pro')], default='Free', max_length=30),
        ),
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='membership',
            name='stripe_plan_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='stripe_customer_id',
            field=models.CharField(max_length=40),
        ),
    ]
