# Generated by Django 3.0.4 on 2020-05-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20200518_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Free', 'free'), ('Starter', 'starter'), ('Basic', 'basic'), ('Pro', 'pro')], default='Free', max_length=30),
        ),
    ]
