# Generated by Django 3.0.4 on 2020-04-18 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200418_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 13, 34, 50, 699839, tzinfo=utc)),
        ),
    ]
