# Generated by Django 3.0.4 on 2020-04-24 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200424_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approve_comment',
            new_name='approved_comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 13, 56, 7, 983887, tzinfo=utc)),
        ),
    ]
