# Generated by Django 3.0.4 on 2020-05-03 20:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20200503_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 20, 59, 49, 501515, tzinfo=utc)),
        ),
    ]
