# Generated by Django 3.0.4 on 2020-05-04 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20200503_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 9, 11, 26, 768547, tzinfo=utc)),
        ),
    ]
