# Generated by Django 3.0.4 on 2020-05-10 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_auto_20200505_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 14, 37, 29, 957822, tzinfo=utc)),
        ),
    ]
