# Generated by Django 3.0.4 on 2020-05-10 15:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_auto_20200510_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 15, 21, 40, 355208, tzinfo=utc)),
        ),
    ]
