# Generated by Django 3.0.4 on 2020-05-15 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0060_auto_20200515_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 12, 10, 55, 676991, tzinfo=utc)),
        ),
    ]
