# Generated by Django 3.0.4 on 2020-04-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200320_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
