# Generated by Django 3.0.4 on 2020-05-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20200418_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_plan_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
