# Generated by Django 3.0.4 on 2020-05-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_stripe_plan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_plan_id',
        ),
    ]
