# Generated by Django 3.0.4 on 2020-05-26 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=200)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='GBP Order Total')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='Email Adress')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('billingName', models.CharField(blank=True, max_length=200)),
                ('billingAddress1', models.CharField(blank=True, max_length=200)),
                ('billingCity', models.CharField(blank=True, max_length=200)),
                ('billingPostCode', models.CharField(blank=True, max_length=200)),
                ('billingCountry', models.CharField(blank=True, max_length=200)),
                ('shippingName', models.CharField(blank=True, max_length=200)),
                ('shippingAddress1', models.CharField(blank=True, max_length=200)),
                ('shippingCity', models.CharField(blank=True, max_length=200)),
                ('shippingPostCode', models.CharField(blank=True, max_length=200)),
                ('shippingCountry', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'Order',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='GBP Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
    ]
